version: '3'

services:
  events:
    build: ./events
    container_name: events
    ports: -8001:8001
  PostgreSQL:
    image: postgres:latest
    container_name: PostgreSQL
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
